### ISSUE TITLE
Linear Regression - Implementation

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#1]
Implement Linear Regression from **Scratch** in the following languages:

- Python
- C++
- Java

Follow guidelines on Readme

**Comment by kajal1122** [comment]
assign it to me

**Comment by a12baghel2** [comment]
**I want to work on this. I want to implement in python _KNN_ and _Linear Regression_.**

**Comment by iam-abbas** [comment]
@kajal1122 @a12baghel2 go ahead create an issue and make a PR 🎉
