### ISSUE TITLE
Modular Neural Network Design

### ISSUE THREAD

**Issue by noahcoder11** [iam-abbas/ML-FromScratch#105]
# ML - Algorithm
- [x] I have not used any Machine Learning Libraries in my code
- [ ] This ML Algorithm is not available in the repository currently.
- [x] If it is, My ML Algorithm is implemented in a different method.
- [x] I have starred this repository

##  Information

- **ML Algorithm Name:** Modular Neural Network Design

- **Language:** Python

**Comment by iam-abbas** [comment]
Go ahead

**Comment by noahcoder11** [comment]
NumPy is permitted, correct? I don't have to code matrix functions?
I did it in JavaScript awhile ago and I had to make all the functions from scratch.

**Comment by iam-abbas** [comment]
Numpy is cool
