### ISSUE TITLE
Linear Regression

### ISSUE THREAD

**Issue by sreyareddy15** [iam-abbas/ML-FromScratch#16]
# ML - Algorithm

- [x] I have not used any Machine Learning Libraries in my code
- [x] This ML Algorithm is not available in the repository currently.
- [x] If it is, My ML Algorithm is implemented in a different method.
- [x] I have starred this repository

##  Information

- **ML Algorithm Name:** linear Regression

- **Language:**  python

**Comment by pranav6670** [comment]
Can I work on this? Thank you!

**Comment by a12baghel2** [comment]
This algorithm is added in python.
