### ISSUE TITLE
Implement Gradient Descent in JavaScript

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#20]
Implement Gradient Descent from scratch in

- JavaScript 

Create new issue according to the template if you would like to implement a different algorithm (or) in a different language.

**Comment by ryzbaka** [comment]
Hi, I'm interested in implementing this. Just to be clear, can we use javascript libraries for reading and parsing the data?

**Comment by iam-abbas** [comment]
@ryzbaka absolutely! I will go ahead and assign you this. Main purpose would be to help beginners understand core concept!
