### ISSUE TITLE
Delete Files and Rename Directory

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#35]
Do the following:- 

- Delete file named 
`LOGISTIC REGRESSION` from root directory
- There are two folders for ”Gradient Descent”. Merge them into one

**Comment by N0ahMC69** [comment]
seems easy enough

**Comment by iam-abbas** [comment]
Feel free to create a PR 🎉

**Comment by N0ahMC69** [comment]
Done @iam-abbas

**Comment by sukhwal13** [comment]
Done @iam-abbas

**Comment by N0ahMC69** [comment]
@sukhwal13 Its already been closed
