### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#55]
Improve Readme:

- Describe the purpose of this repository (briefly described already)
- Fix grammar issues
- More detailed information about repository (Briefly mentioned currently)

**Comment by everlearner** [comment]
Hey @iam-abbas, can I take this issue?

**Comment by Mayank662** [comment]
Hi @iam-abbas Please assign me this issue.

**Comment by iam-abbas** [comment]
I will accept the first PR :D

**Comment by iam-abbas** [comment]
stale
