### ISSUE TITLE
[Logistic regression]

### ISSUE THREAD

**Issue by Nitin1901** [iam-abbas/ML-FromScratch#57]
# ML - Algorithm
- [x] I have not used any Machine Learning Libraries in my code
- [ ] This ML Algorithm is not available in the repository currently.
- [x] If it is, My ML Algorithm is implemented in a different method.
- [ ] I have starred this repository

##  Information

- **ML Algorithm Name: Logistic regression**

- **Language: Python**

**Comment by iam-abbas** [comment]
Go ahead @Nitin1901 make sure you save it in right directory and if it already exists save it in 
`/Python Approach 2`

**Comment by Nitin1901** [comment]
@iam-abbas created a pull request. Please review.
