### ISSUE TITLE
Create Python Notebook for KNN

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#65]
Create a Python Notebook for to demonstrate:

- KNN Classifier

save it at: 
```
[root]/Notebooks/UsingLibs/[Algorithm Name]/[Algorithm].ipynb
```

Create a new issue according to the template if you would like to implement a different algorithm (or) in a different language.

**Comment by Varun221** [comment]
I have made a notebook that can satisfy the needs of the issue. Can I submit a PR?

**Comment by iam-abbas** [comment]
Perfect! Go agead @Varun221
