### ISSUE TITLE
Regularization for Linear Regression.

### ISSUE THREAD

**Issue by Varun221** [iam-abbas/ML-FromScratch#67]
# ML - Algorithm
- [x] I have not used any Machine Learning Libraries in my code
- [x] This ML Algorithm is not available in the repository currently.
- [x] If it is, My ML Algorithm is implemented in a different method.
- [x] I have starred this repository

##  Information

- **ML Algorithm Name:**
Linear Regression *with Regularization*
Added extra prompts too, for better outputs while program execution.

- **Language:**
python.

**Comment by iam-abbas** [comment]
Go ahead and create a PR @Varun221

**Comment by iam-abbas** [comment]
Implemented in #68
