### ISSUE TITLE
Linear Regression - C++

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#7]
Implement Linear Regression from scratch in

- C++

Create new issue according to the template if you would like to implement a different algorithm (or) in a different language.

**Comment by Nikhil-1503** [comment]
Assign this to me.

**Comment by je117er** [comment]
Hi @iam-abbas, can you assign this issue to me? Thank you.

**Comment by pikachu28** [comment]
I would like to work on this issue : )

**Comment by iam-abbas** [comment]
go ahead @pikachu28

**Comment by divyavit** [comment]
Hi, can I also contribute to this issue ?

**Comment by iam-abbas** [comment]
if you are interested you could implement any ML Algorithm in Any language from scratch. just create and issue with the template and create PR

**Comment by divyavit** [comment]
Okay got it.. thanks!
