### ISSUE TITLE
Implement Linear Regression in Java

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#89]
##  Information

- **ML Algorithm Name:** Linear Regression 

- **Language:** Java

**Comment by capt-doki** [comment]
Hi,
Can you please assign this issue to me. Implementing a ML model in java seems interesting

Thanks

**Comment by capt-doki** [comment]
Hi @iam-abbas ,
Can you please assign this issue to me. Implementing a ML model in C seems interesting

Thanks

**Comment by capt-doki** [comment]
Hi @iam-abbas 
Can you please assign this issue to me. Implementing a Linear Regression in java seems interesting

Thanks
