### ISSUE TITLE
Implement Random Forest in any language of choice

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/ML-FromScratch#93]
Implement Random Forest in any language of choice. First create an issue using the given template and follow guidelines on Readme

**Comment by capt-doki** [comment]
Hi @iam-abbas 
Can you please assign this issue to me. Implementing a Random Forest seems interesting

Thanks

**Comment by iam-abbas** [comment]
> Hi @iam-abbas 
> 
> Can you please assign this issue to me. Implementing a Random Forest seems interesting
> 
> 
> 
> Thanks

Done
